use_frameworks!

platform :ios, '9.0'

target 'GPLottie_Example' do
  pod 'GPLottie', :git => 'https://github.com/zinzin186/GPLottie.git'

  target 'GPLottie_Tests' do
    inherit! :search_paths

    
  end
end
